
package com.mycompany.teste;

/**
 *
 * @author Gasparzinho
 */
public class JanelaCalculadora extends javax.swing.JFrame{
    
    private javax.swing.JButton dividir;
    private javax.swing.JTextField entradaValor1;
    private javax.swing.JTextField entradaValor2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton limpaTudo;
    private javax.swing.JButton multiplicar;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JTextField operacaoEscolhida;
    private javax.swing.JButton resultado;
    private javax.swing.JTextField saidaResultado;
    private javax.swing.JButton somar;
    private javax.swing.JButton subtrair;
    
    private String valor1 = "0";
    private String valor2 = "0";
    private String juntaValores;
    private String operacaoEsco;
    private float saida;
    private boolean digitouOperacao = false;
    
    /**
     * Creates new form testeee
     */
    public JanelaCalculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        entradaValor1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        somar = new javax.swing.JButton();
        subtrair = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        resultado = new javax.swing.JButton();
        limpaTudo = new javax.swing.JButton();
        operacaoEscolhida = new javax.swing.JTextField();
        entradaValor2 = new javax.swing.JTextField();
        saidaResultado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Básica");
        setResizable(false);

        entradaValor1.setEditable(false);
        entradaValor1.setBackground(new java.awt.Color(255, 255, 255));
        entradaValor1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        entradaValor1.setText("0");
        entradaValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaValor1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        num1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        num1.setText("    1    ");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        num2.setText("    2    ");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        num3.setText("    3    ");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        num4.setText("    4    ");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        num5.setText("    5    ");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        num6.setText("    6    ");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        num7.setText("    7    ");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        num8.setText("    8    ");
        num8.setToolTipText("");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        num9.setText("    9    ");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        num0.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        num0.setText("    0    ");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(num1)
                        .addGap(18, 18, 18)
                        .addComponent(num2)
                        .addGap(18, 18, 18)
                        .addComponent(num3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(num4)
                        .addGap(18, 18, 18)
                        .addComponent(num5)
                        .addGap(18, 18, 18)
                        .addComponent(num6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(num7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num0)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(num8)
                                .addGap(18, 18, 18)
                                .addComponent(num9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        somar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        somar.setText("    +    ");
        somar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somarActionPerformed(evt);
            }
        });

        subtrair.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        subtrair.setText("    -    ");
        subtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtrairActionPerformed(evt);
            }
        });

        dividir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        dividir.setText("    /    ");
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });

        multiplicar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        multiplicar.setText("    *    ");
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });

        resultado.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        resultado.setText("    =    ");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        limpaTudo.setText("Limpar Campos");
        limpaTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaTudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(limpaTudo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(somar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subtrair))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(somar)
                .addGap(18, 18, 18)
                .addComponent(subtrair)
                .addGap(18, 18, 18)
                .addComponent(dividir)
                .addGap(18, 18, 18)
                .addComponent(multiplicar)
                .addGap(18, 18, 18)
                .addComponent(resultado)
                .addGap(18, 18, 18)
                .addComponent(limpaTudo)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        operacaoEscolhida.setEditable(false);
        operacaoEscolhida.setBackground(new java.awt.Color(255, 255, 255));
        operacaoEscolhida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        operacaoEscolhida.setText("?");
        operacaoEscolhida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacaoEscolhidaActionPerformed(evt);
            }
        });

        entradaValor2.setEditable(false);
        entradaValor2.setBackground(new java.awt.Color(255, 255, 255));
        entradaValor2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        entradaValor2.setText("0");
        entradaValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaValor2ActionPerformed(evt);
            }
        });

        saidaResultado.setEditable(false);
        saidaResultado.setBackground(new java.awt.Color(255, 255, 255));
        saidaResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        saidaResultado.setText("?");
        saidaResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaResultadoActionPerformed(evt);
            }
        });

        jLabel1.setText("1º valor");

        jLabel2.setText("operação");

        jLabel3.setText("2º valor");

        jLabel4.setText("resultado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(operacaoEscolhida, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entradaValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(saidaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operacaoEscolhida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradaValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saidaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {                                        
        this.operacao("/");
    }                                       

    private void entradaValor1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
    }                                             

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.setaValoresDigitados("1");        
    }                                    

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {                                          
       
        realizaOperacao();     
        
    }                                         

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.setaValoresDigitados("2");
    }                                    

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.setaValoresDigitados("3");
    }                                    

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.setaValoresDigitados("4");
    }                                    

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.setaValoresDigitados("5");
    }                                    

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.setaValoresDigitados("6");
    }                                    

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.setaValoresDigitados("7");
    }                                    

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.setaValoresDigitados("8");
    }                                    

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.setaValoresDigitados("9");
    }                                    

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.setaValoresDigitados("0");
    }                                    

    private void somarActionPerformed(java.awt.event.ActionEvent evt) {                                      
        this.operacao("+");
    }                                     

    private void subtrairActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.operacao("-");
    }                                        

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        this.operacao("*");
    }                                           

    private void operacaoEscolhidaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void entradaValor2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void saidaResultadoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void limpaTudoActionPerformed(java.awt.event.ActionEvent evt) {                                          
       this.limpaTodosOsCampos();
       this.desativaAtivaBotoes(true);
    }                                         
   
    private void realizaOperacao(){
        
        if(digitouOperacao == true){
            
            if(operacaoEscolhida.getText().equals("+")){
                this.saida = Float.parseFloat(entradaValor1.getText()) + Float.parseFloat(entradaValor2.getText());
            }
            else if(operacaoEscolhida.getText().equals("-")){
                this.saida = Float.parseFloat(entradaValor1.getText()) - Float.parseFloat(entradaValor2.getText());
            }
            else if(operacaoEscolhida.getText().equals("*")){
                this.saida = Float.parseFloat(entradaValor1.getText()) * Float.parseFloat(entradaValor2.getText());
            }
            else{
                this.saida = Float.parseFloat(entradaValor1.getText()) / Float.parseFloat(entradaValor2.getText());
            }
            
            digitouOperacao = false;
            saidaResultado.setText(""+this.saida);
            this.desativaAtivaBotoes(false);
        }
    }
    
    private void desativaAtivaBotoes(boolean op){
        num0.setEnabled(op);
        num1.setEnabled(op);
        num2.setEnabled(op);
        num3.setEnabled(op);
        num4.setEnabled(op);
        num5.setEnabled(op);
        num6.setEnabled(op);
        num7.setEnabled(op);
        num8.setEnabled(op);
        num9.setEnabled(op);
        somar.setEnabled(op);
        subtrair.setEnabled(op);
        multiplicar.setEnabled(op);
        dividir.setEnabled(op);
        resultado.setEnabled(op);
    }
    
    private void operacao(String op){        
        if(entradaValor1.getText().equals("0")){
            this.digitouOperacao = false;
        }
        else{
            operacaoEscolhida.setText(op);
            this.digitouOperacao = true;
        }        
    }
    
    private void limpaTodosOsCampos(){
        entradaValor1.setText("0");
        operacaoEscolhida.setText("?");
        entradaValor2.setText("0");
        saidaResultado.setText("?");
        this.digitouOperacao = false;
    }
    
    private void setaValoresDigitados(String valor){     
        if(digitouOperacao == false){            
            if(entradaValor1.getText().equals("0")){
                this.juntaValores = valor;
            }
            else{
                this.juntaValores += valor;
            }
            entradaValor1.setText(this.juntaValores);
        }
        else{
            if(entradaValor2.getText().equals("0")){
                this.juntaValores = valor;
            }
            else{
                this.juntaValores += valor;
            }
            entradaValor2.setText(this.juntaValores);
        }        
    }  

    
}
